Moved the importer script to a git subdirectory
CamioCam/examples pull request #14
Opened 2017-05-01 23:06 UTC by jhallard

It will now automatically track the video-importer repo owned by
tnc-ca-geo.

2017-05-03 00:06 UTC, jcmaslan approved these changes
2 minor requests but otherwise LGTM

2017-05-03 00:06 UTC, jcmaslan commented on batch_import/README.md
> +@TODO - discuss the Camio API that allows one to query for the status of a job (in progress vs completed).
OK to include http://api.camio.com/#jobs now with reference to http://api.camio.com/#get-specific-job

2017-05-03 00:06 UTC, jcmaslan commented on batch_import/camio_hooks.py
> +        location(opt) - a string describing the location of the camera (Example lat-long)
Example should be the specific json String example `{"location:" {"lat": 7.367598, "lng":134.706975}, "accuracy":5.0}`

2017-05-05 21:38 UTC, jcmaslan requested changes
Ping me with any other clarifications needed.

2017-05-05 21:38 UTC, jcmaslan commented on batch_import/EXAMPLE.md
> +Once the script has completed sending videos to Box for segmentation and first-order analysis, the video clips will begin to be available to search through on [your Camio feed](https://www.camio.com/
https://www.camio.com/app/#search

2017-05-05 21:38 UTC, jcmaslan commented on batch_import/EXAMPLE.md
> +3. An OAuth token for your Camio account (gotten from [the integrations page](https://www.camio.com/settings/integrations))
https://www.camio.com/settings/integrations/#api

2017-05-05 21:38 UTC, jcmaslan commented on batch_import/EXAMPLE.md
> +4. The Camio Box IP-address (explained in the [section](#get-the-camio-box-ip-address))
the [get ip address](#get-the-camio-box-ip-address) section

2017-05-05 21:38 UTC, jcmaslan commented on batch_import/EXAMPLE.md
> +6. A regular-expression describing how to parse your input videos ([described here](#constructing-the-file-parsing-regex))
regular expression describing how to parse your input video filenames

2017-05-05 21:38 UTC, jcmaslan commented on batch_import/EXAMPLE.md
> +Once you have all of the items listed above, you can start to batch-import videos to Camio
. at end of sentence

2017-05-05 21:38 UTC, jcmaslan commented on batch_import/EXAMPLE.md
> +Your Camio Box needs to be powered on, registered under your account, and on the same local-network as the computer running the batch-importer script.
local network

2017-05-05 21:38 UTC, jcmaslan commented on batch_import/EXAMPLE.md
> +#### Obtain the video-import Script and the Camio-specific Hooks Code
Clone the importer and use the Camio Hooks

2017-05-05 21:38 UTC, jcmaslan commented on batch_import/EXAMPLE.md
> +For the video-import script to work properly with Camio and the [Camio Hooks](examples/batch_import/camio_hooks.py) module, a few environment
camio_hooks.py (the python module so as not to confuse with the general concept of Camio Hooks)

2017-05-05 21:38 UTC, jcmaslan commented on batch_import/EXAMPLE.md
> +| `CAMIO_BOX_DEVICE_ID` | set this to the `device_id` of the [Camio Box](https://camio.com/box) that's processing your imported video files. You can get your  `device_id` from your [/boxes](https://c
missing completion of sentence about getting device_id

2017-05-05 21:38 UTC, jcmaslan commented on batch_import/EXAMPLE.md
> +You need to know the local-IP address of your Camio Box. You can do this in many ways but the two easiest are
local IP address

2017-05-05 21:38 UTC, jcmaslan commented on batch_import/EXAMPLE.md
> +# on OSX
arp-scan on OS X

2017-05-05 21:38 UTC, jcmaslan commented on batch_import/EXAMPLE.md
> +# on Linux (Ubuntu)
arp-scan on Linux

2017-05-05 21:38 UTC, jcmaslan commented on batch_import/EXAMPLE.md
> +**On OSX**
route on OS X

2017-05-05 21:38 UTC, jcmaslan commented on batch_import/EXAMPLE.md
> +**On Linux**
route on Linux

2017-05-05 21:38 UTC, jcmaslan commented on batch_import/EXAMPLE.md
> +Download the [Fing application](https://www.fing.io/) to your phone. Open the app and click the 'refresh' button on the top bar. Ths will kick off a scan
This

2017-05-05 21:38 UTC, jcmaslan commented on batch_import/EXAMPLE.md
> +of the network, displaying all of the devices that it has located. Look through the list for the MAC address of your Camio Box and note down the IP-address listed.
IP address

2017-05-05 21:38 UTC, jcmaslan commented on batch_import/EXAMPLE.md
> +For the sake of the example, let's say that your directory of video files for batch-import is located at `~/batch_videos/`, and the files have the
filenames have the format of

2017-05-05 21:38 UTC, jcmaslan commented on batch_import/EXAMPLE.md
> +Then you would use the following string as the regular-expression passed to the video-import script.
regular expression

2017-05-05 21:38 UTC, jcmaslan commented on batch_import/EXAMPLE.md
> +Run the importer with all of the values we've assembled in the previous steps
add period

2017-05-05 21:38 UTC, jcmaslan commented on batch_import/EXAMPLE.md
> +  --host 192.168.1.57 \
Make this 192.168.1.51 or change 192.168.1.51 to 192.168.1.57 to be consistent with your scan example above.

2017-05-05 21:38 UTC, jcmaslan commented on batch_import/EXAMPLE.md
> +Params: {'job_id': None, 'timestamp': '2016-10-08T17:02:27.000', 'uploaded_on': None, 'filename': '/Users/user/natconv_test/CAMERA_FRONT-rand-1475971347.mp4', 'shard_id': None, 'camera': 'CAMERA_FRON
Why these None values?

2017-05-05 21:38 UTC, jcmaslan commented on batch_import/EXAMPLE.md
> +If you get any errors about missing the Device ID of the Camio Box or an unauthenticated error, try to set the environment variables again. To check that the environment variables
`device_id` and add link to [set the environment variables]

2017-05-05 21:38 UTC, jcmaslan commented on batch_import/EXAMPLE.md
> +You can search for the name of the camera (that was parsed from the filenames) to see the videos that have been uploaded.
uploaded from that camera.

2017-05-05 21:38 UTC, jcmaslan commented on batch_import/EXAMPLE.md
> +We are currently writing some tools to help you recover all of the labels that were generated for the batch-imported videos, but this tool is not available yet. We are also designing tools and an API
Camio will soon include tools...
The tools will include an API to check on the status...

2017-05-05 21:38 UTC, jcmaslan commented on batch_import/README.md
> +The open source [video importer](https://github.com/tnc-ca-geo/video-importer) allows one to specify a set of hooks that describe how the importer
you (since "one" sounds stilted)

2017-05-05 21:38 UTC, jcmaslan commented on batch_import/README.md
> +should interact with the segmentation and labeling service of your choosing. To use the video-importer with the Camio service, one must supply the
you

2017-05-05 21:38 UTC, jcmaslan commented on batch_import/README.md
> +The full documentation of the Jobs API can be found [here](api.camio.com/#jobs). To get information about a specific job given a job ID, you would do the following.
[Jobs API]

2017-05-05 21:38 UTC, jcmaslan commented on batch_import/camio_hooks.py
> +CAMIO_REGISTER_URL="https://test.camio.com/api/cameras/discovered"
document for production rather than test

2017-05-05 21:38 UTC, jcmaslan commented on batch_import/camio_hooks.py
> +CAMIO_JOBS_URL = "https://test.camio.com/api/jobs"
www

2017-05-05 21:38 UTC, jcmaslan commented on camera_registration/README.md
> +To connect a camera stream to Camio, one needs to register the camera source through our API. Normally this is done automatically by a Camio Box
remove "stream"

2017-05-05 21:38 UTC, jcmaslan commented on camera_registration/README.md
> +that scans your local network, identified all of the cameras, and automatically registers them. If you have a camera that is not recognized by
identifies

2017-05-05 21:38 UTC, jcmaslan commented on camera_registration/README.md
> +Camio Box, you can manually register it using the [register_camera](register_camera.py) script that we provide.
remove "that we provide" since you link to it.

2017-05-05 21:38 UTC, jcmaslan commented on camera_registration/README.md
> +this script allows one to register a camera source with the Camio service through
you

2017-05-05 21:38 UTC, jcmaslan commented on camera_registration/README.md
> +the /api/devices/registered endpoint. Camera registration is normally done automatically
/api/cameras/discovered

2017-05-05 21:38 UTC, jcmaslan commented on camera_registration/README.md
> +that it finds, this script allows one to register a camera that a Camio Box doesn't know how to recognize.
you

2017-05-05 21:38 UTC, jcmaslan commented on camera_registration/README.md
> +This script is meant to be used by 3rd parties who wish to use their cameras/nvrs/dvrs with the Camio service,
stay with 2nd person you rather than switching to 3rd person they/their.

2017-05-05 21:38 UTC, jcmaslan commented on camera_registration/README.md
> +To connect a camera to your Camio account, you must specify the Camio Box device that you will be connecting the camera
`device_id` that will connect your camera to Camio servers.

2017-05-05 21:38 UTC, jcmaslan commented on camera_registration/README.md
> +to our servers through. You do this by providing the device ID of the Camio Box to this script. Currently, the easiest way
global replace on our and we

2017-05-05 21:38 UTC, jcmaslan commented on camera_registration/README.md
> +to get the device ID is by going to your https://www.camio.com/boxes page and getting the device ID out of the URL.
make the url a link

2017-05-05 21:38 UTC, jcmaslan commented on camera_registration/README.md
> +(the URL will look like: https://www.camio.com/boxes?device_id=AABBCCDDEFFAABBDDEEFFCC, grab the AABBCCDDEFFAABBDDEEFFCC part)
#device_id (not ?)

2017-05-05 21:38 UTC, jcmaslan commented on camera_registration/README.md
> +*NOTE* - Camio only supports H264 encoded video streams, mjpeg, etc. will not work.
H.264

2017-05-05 21:38 UTC, jcmaslan commented on camera_registration/README.md
> +You can place these as {{placeholder}} anywhere inside of the RTSP URL, and we will fill in the appropriate values before attempting to
Camio

2017-05-05 21:38 UTC, jcmaslan commented on camera_registration/README.md
> +positional arguments:
remove "positional"

2017-05-05 21:38 UTC, jcmaslan commented on camera_registration/README.md
> +Below is an example of how to run the script to register a camera with our service. The camera connection parameters are listed,
with Camio.

2017-05-05 21:38 UTC, jcmaslan commented on camera_registration/README.md
> +| name    |  my_new_camera |
Front Entrance

2017-05-05 21:38 UTC, jcmaslan commented on camera_registration/README.md
> +you would do the following:
execute the command:

2017-05-05 21:38 UTC, jcmaslan commented on camera_registration/register_camera.py
> +this script allows one to register a camera source with the Camio service through
global replace "one" to "you"

2017-05-05 21:38 UTC, jcmaslan commented on camera_registration/register_camera.py
> +that it finds, this script allows one to register a camera that a Camio Box doesn't know how to recognize.
replace comma with period for new sentence.

2017-05-05 21:38 UTC, jcmaslan commented on camera_registration/register_camera.py
> +This script is meant to be used by 3rd parties who wish to use their cameras/nvrs/dvrs with the Camio service,
same comment as above about sticking with 2nd person you

2017-05-05 21:38 UTC, jcmaslan commented on camera_registration/register_camera.py
> +To connect a camera to your Camio account, you must specify the Camio Box device that you will be connecting the camera
copy from duplicate content above after updating language

2017-05-05 21:38 UTC, jcmaslan commented on camera_registration/register_camera.py
> +    parser.add_argument('auth_token', type=str, help='your Camio auth token (see https://www.camio.com/settings/integrations)')
integrations#api

2017-05-05 21:38 UTC, jcmaslan commented on camera_registration/register_camera.py
> +    parser.add_argument('auth_token', type=str, help='your Camio auth token (see https://www.camio.com/settings/integrations)')
OAuth token

2017-05-05 21:38 UTC, jcmaslan commented on hooks/hook-example.py
> +#      timestamp: {u'meta_class': u'datetime.datetime', u'date': u'2017-05-05T01:31:13.738647'},
public API should use regular json and ISO8601 timestamp strings

2017-05-05 21:38 UTC, jcmaslan commented on hooks/hook-install.sh
> +nohup gunicorn -w 2 -b 0.0.0.0:80 hook-example:app > /tmp/gunicorn.log &
I think you said 8080 as port elsewhere in the doc so check that port is same throughout.

2017-05-05 21:38 UTC, jcmaslan commented on hooks/hook-register.sh
> +usage="bash $0 auth_token callback_url query"
parsed_query

2017-05-05 21:38 UTC, jcmaslan commented on hooks/{}
> +HTTP/1.1 200 OK
what is this file?

2017-05-05 22:44 UTC, jhallard commented on hooks/hook-example.py
> +#      timestamp: {u'meta_class': u'datetime.datetime', u'date': u'2017-05-05T01:31:13.738647'},
Okay this is an api change that we have to coordinate server side

2017-05-05 22:44 UTC, jhallard commented on hooks/hook-example.py
> +#      timestamp: {u'meta_class': u'datetime.datetime', u'date': u'2017-05-05T01:31:13.738647'},
@mdipierro ^^

2017-05-05 22:45 UTC, jhallard commented on hooks/hook-install.sh
> +nohup gunicorn -w 2 -b 0.0.0.0:80 hook-example:app > /tmp/gunicorn.log &
that's different, box-server runs on 8080. This is the hook that runs on port 80.

2017-05-05 22:47 UTC, jhallard commented on hooks/{}
> +HTTP/1.1 200 OK
I'm not sure why this keeps popping up, one of our redirections isn't working correctly.. looking..

2017-05-05 23:11 UTC, jcmaslan requested changes
still TODOs with "our" and punctuation

2017-05-05 23:11 UTC, jcmaslan commented on camera_registration/README.md
> +This script allows you to connect your cameras/nvrs/dvrs with the Camio service,
period then new sentence

2017-05-05 23:26 UTC, jcmaslan approved these changes

2017-05-05 23:29 UTC, merged