Documentation updates (mostly), some log output cleaning.
CamioCam/examples pull request #36
Opened 2017-05-24 22:52 UTC by jhallard

No major code or API logic changes

2017-05-24 23:24 UTC, jcmaslan requested changes

2017-05-24 23:24 UTC, jcmaslan commented on batch_import/README.md
> +In the example above, the Camio Box that's receives the videos:
the Camio Box receives the videos and:

2017-05-24 23:24 UTC, jcmaslan commented on batch_import/README.md
> +time range while downloading all of the labels that Camio has annotated the events with.
@jhallard please use the language I previously suggested before this change:

This script accepts a Camio `job_id`, finds the time-boundaries and cameras associated with that job, and iterates over that time range while downloading all of the labels that Camio has assigned to those events.

2017-05-24 23:24 UTC, jcmaslan commented on batch_import/README.md
> +This script is designed to be used after a batch-import job has been completed and you wish to retreive a
please revert to prior language

2017-05-24 23:24 UTC, jcmaslan commented on batch_import/README.md
> +                        {job_id}_results.json)
use {{jobs_id}} for consistent mustaches

2017-05-24 23:24 UTC, jcmaslan commented on batch_import/README.md
> +    Here is an example of how to run the script to recover a dictionary of lables for the last job that you
This isn't for the last job but rather the particular `job_id` and "recover" sounds like disaster recovery so just say:

Here is an example of how to run the script to download all labels for the `job_id` `SjksdkjoowlkjlSDFiwjoijerSDRdsdf`

2017-05-24 23:24 UTC, jcmaslan commented on batch_import/download_labels.py
> +    submitted. This will obtain the bookmark of labels for the job with job_id "SjksdkjoowlkjlSDFiwjoijerSDRdsdf" and
duplicate language above, so please propagate requested changes.

2017-05-25 00:08 UTC, jcmaslan requested changes
only camera name regex and value is important

2017-05-25 00:08 UTC, jcmaslan commented on batch_import/EXAMPLE.md
>  🍺  /usr/local/Cellar/curl/7.54.0: 392 files, 2.8MB
way to get rid of the beer mug? no biggy (funny)

2017-05-25 00:08 UTC, jcmaslan commented on batch_import/EXAMPLE.md
> +This captures the `C2_Hi20161009` part as the camera name (used for registering the camera with Camio), and parses the `1476014557` part as the Unix-timestamp
@jhallard `C2_Hi` is the camera name (camera 2 high resolution stream), so modify the regex to avoid including the date in the camera name.

2017-05-25 00:08 UTC, jcmaslan commented on batch_import/EXAMPLE.md
> +> --regex ".*/(?P<camera>\w+?)\-.*\-(?P<epoch>\d+)\.mp4" \
remember to update all occurrences of regex per request above for `C2_Hi`

2017-05-25 00:08 UTC, jcmaslan commented on batch_import/EXAMPLE.md
> +import_video.py,  INFO:      get_params():139:   camera_name: C2_Hi20161009
update all camera_name values with new C2_Hi too.

2017-05-25 00:08 UTC, jcmaslan commented on batch_import/README.md
> +        "name": "C2_Hi20161009"
remember to update camera names

2017-05-25 04:19 UTC, jcmaslan requested changes

2017-05-25 04:19 UTC, jcmaslan commented on batch_import/README.md
> +        "yellowfin",
@jhallard the labler needs to use "yellowfin tuna", "bluefin tuna" to match your whitelist, and remove "bass" and "trout" just to keep in salt water family (even though fake demo)

2017-05-25 04:19 UTC, jcmaslan commented on batch_import/samples/sample_hook_data.json
> +  "labels": {
@jhallard something's wrong since this file is now output rather than the intended hook data.

2017-05-25 06:38 UTC, jcmaslan approved these changes

2017-05-25 06:38 UTC, merged

2017-05-25 06:40 UTC, jhallard commented on batch_import/README.md
> +        "yellowfin",
done